---
title: "Terga1"
output: html_document
date: '2022-04-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load the packages}
# load the library
library(predomics)
library(ggplot2)
library(gridExtra)
library(pROC)
library(reshape2)
```




```{r oading filtering the data, message=FALSE, warning=FALSE, paged.print=FALSE}
# load the data
data("cir_train")
str(cir_train, max.level = 1)
# Filter the non informative variables
X <- cir_train$X; y <- cir_train$y # set global variables
X <- X[rowSums(X)!=0,]; dim(X) # filter out variables with only zero values
X <- filterNoSignal(X = X, side = 1, threshold = "auto", verbose = FALSE); dim(X) 

```

```{r}
cir_train$y <-c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3)
y <- cir_train$y
y
```


```{r}
# Terga1
clf <- terga1(nCores = 1, 
              seed = 1, 
              plot = TRUE,
              sparsity = c(2:10)
)
printy(clf) # print the object for more information
isClf(clf)  # test whether the object is a classifier
class(clf)  # the class of the classifier object
```


```{r}
runit = TRUE
if(runit)
{ 
  for(i in 1:length(unique(y))){
  y <- ifelse(cir_train$y==class[i],1,0)
  res_clf <- fit(X = X, y = y, clf = clf, cross.validate = TRUE, nfolds = 10); #class(res_clf)
  # save results
 save(res_clf, clf, file = "cirrhosis1_res_clf_terga1", compression_level = 9)}
}
   # logits <- glm(injury~.,data=biotrainlog, family=binomial(link = "logit"))

```

